# Generated by Django 3.2.3 on 2021-10-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_product_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.TextField(blank=True),
        ),
    ]
